version: '3.8'
services:
  app:
    build:
      context: .
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=ep-lucky-scene-a13gac0r.ap-southeast-1.aws.neon.tech
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=scheduler_owner
      - POSTGRES_PASSWORD=7dAbBeq4vZFg
      - POSTGRES_DATABASE=scheduler
      - POSTGRES_SSL=true
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
    command: npm run start:dev
